In [1]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

In [2]:
data = asarray([['red'], ['grean'], ['blue']])

In [3]:
print(data)

[['red']
 ['grean']
 ['blue']]


In [7]:
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')

In [8]:
onehot = encoder.fit_transform(data)

In [9]:
print(onehot)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
